# .pre-commit-config.yaml
# fail_fast: true
# repos:
#   - repo: https://github.com/psf/black
#     rev: stable
#     hooks:
#       - id: black
#   - repo: https://github.com/PyCQA/pylint
#     rev: v3.0.0
#     hooks:
#       - id: pylint

# pip install pre-commit
# pre-commit install
# pre-commit run --all-files

# # Local
# fail_fast: true

# repos:

# - repo: local
#   hooks:

#   - id: ruff
#     name: ruff
#     entry: python -m ruff check . --fix
#     language: system
#     types: [python]

#   - id: ruff-format
#     name: ruff-format
#     entry: python -m ruff format .
#     language: system
#     types: [python]

#   - id: mypy
#     name: mypy
#     entry: python -m mypy
#     language: system
#     types: [python]

fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]

      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy